### PR TITLE
Add new ble_peripheral examples and new libraries.

### PR DESCRIPTION
**Pull request by Cierpliwy**
New examples:
* ble_app_multiperipheral
* ble_app_queued_writes
* bluetoothds_template
* ble_app_lls
* ble_app_ias_c

New libraries:
* nrf5_section_fwd
* nrf5_sortlist
* nrf5_assert
* nrf5_hardfault
* nrf5_hardfault_handler
* crc16 library
* nrf5_ble_srv_lls
* nrf5_ble_srv_ias_c
    
Library changes:
* ~~Cleanup nrf5_crypto library~~
* Exclude from all nrf5_soc
* ~~Fix forward definitions for nrf5_log_fwd~~

Other:
* Improve check_coverage.sh script

### CODE REVIEW

**Comment by Cierpliwy** [comment]
I'm still not sure how to approach it. I understood that `nrf5_log_fwd` is there to mark dependencies relying on the log functionality. If you are not logging, you can skip `nrf5_log`. Therefore in the dependency, which uses log I probably should use `nrf5_log_fwd` instead of `nrf5_log`. However, there is a problem, when example actually have logs enabled. When this happens ""nrf_strerror.h" is included as well and dependency relying on the `nrf5_log_fwd` doesn't compile.

**Comment by borys-jelenski-polidea** [comment]
I'm not sure I fully understand - can you give a more specific example?

**Comment by Cierpliwy** [comment]
I added nrf5_sortlist:
```json
"nrf5_sortlist": {
    "documentation": "Sorted list library",
    "variant": "object",
    "sources": [
      "components/libraries/sortlist/nrf_sortlist.c"
    ],
    "includes": {
      "public": [
        "components/libraries/sortlist",
        "components/libraries/util"
      ]
    },
    "dependencies": {
      "public": [
        "nrf5_config",
        "nrf5_mdk",
        "nrf5_soc",
        "nrf5_log_fwd"
      ]
    }
  },
```
I didn't specify `nrf5_log` dependency, but `nrf5_log_fwd`. This will not pull in any log dependencies automatically. However, this library (object file) won't compile if NRF_LOG_ENABLED is defined without changes introduced in this PR. This is due to "nrf_strerror.h" header file, which was missing in that case.

**Comment by borys-jelenski-polidea** [comment]
OK, so I conducted a simple experiment. I added the `nrf5_sortlist` library:
``` cmake
# Sorted list
add_library(nrf5_sortlist OBJECT EXCLUDE_FROM_ALL
  "${NRF5_SDK_PATH}/components/libraries/sortlist/nrf_sortlist.c"
)
target_include_directories(nrf5_sortlist PUBLIC
  "${NRF5_SDK_PATH}/components/libraries/sortlist"
  "${NRF5_SDK_PATH}/components/libraries/util"
)
target_link_libraries(nrf5_sortlist PUBLIC
  nrf5_config
  nrf5_log
  nrf5_mdk
  nrf5_soc
)
```
So as you can see, it pulls `nrf5_log` (not the forward interface).

Then I just took some example form the `peripheral` group and I modified it's `sdk_config.h` so the `nrf_sortlist` is enabled and has logging enabled on UART. I artificially added the `nrf5_sortlist` target as a dependency for this example. It won't be used in the final binary of course but it will definitely be built before final linking. I can build the whole example and the `nrf5_sortlist` individually.

I also took a look on one of the examples you added: `ble_peripheral/experimental/ble_app_queued_writes`. I added support for it manually using my empiric approach and it seems the `nrf_sortlist` library is not used there as the example can be built without specifying it as a dependency. I noticed the the `libraries/sortlist` include directory shows up in the Makefile of the example however, I seems it is not used.

What would happen if you used the `nrf5_log` in the dependencies of `nrf5_sortlist` instead of the forwarding interface `nrf5_log_fwd`?

**Comment by Cierpliwy** [comment]
It would work. I wrongly assumed that nrf5_log_fwd exists not only to solve cyclic dependencies but also to make other libraries dependencies smaller by not pulling a lot of cruft.

I'll fix the PR.

**Comment by borys-jelenski-polidea** [comment]
Great. Perhaps I explained my intentions for `nrf5_log_fwd` imprecisely, sorry for that.

Looks fine now, I'll let the CI complete the pipeline and I'm merging.

**Pull request merged**
